# Generated by Django 3.1.2 on 2020-11-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0003_auto_20201106_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transação',
            options={'verbose_name_plural': 'Transações'},
        ),
        migrations.AddField(
            model_name='transação',
            name='observações',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='transação',
            name='data',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
