# Generated by Django 3.1.2 on 2020-11-06 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_auto_20201106_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transação',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
